[bugfix] AttributeError in refresh.template.py
AttributeError: 'bool' object has no attribute 'relative_to'

- Bug introduced during the reversion of changes (https://github.com/hedronvision/bazel-compile-commands-extractor/commit/0b821b7e4286aec887757461366f6eaaa0972cb9#diff-a1d7061df7c566a1f7656624ec608ad53dd3aff7a7789b9b6e4866a3b1616042R502).
- Reverted to the previous implementation to fix the issue.